server:
  port: 18500

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.106:8848
        namespace: c58032ec-9a6d-4259-9be5-287a80d6a21c
        group: gateway
    gateway:
      routes:
        - id: SalaryService
          uri: http://localhost:18501
          predicates:
            - Path=/xst/salary/**
  application:
    name: xts-gateway


