server:
  port: 18500

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.101:8848
    gateway:
      routes:
        - id: SalaryService
          uri: http://localhost:18501
          predicates:
            - Path=/xst/salary/**
        - id: UserService
          uri: http://localhost:18502
          predicates:
            - Path=/xst/user/**
  application:
    name: xts-gateway


